title: Gauthami Kuravi # your name (or website title) here
logo: "/images/20190903_210137062_iOS.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  <br>Expierenced  IT professional with more than 3 years of expertise in Analytics and ETL process.<br>
  <br><br>
  <a href="https://www.linkedin.com/in/gauthami-k-617b01192/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
